-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Apr 18, 2017 at 09:19 PM
-- Server version: 10.1.9-MariaDB
-- PHP Version: 5.6.15

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `proj_india`
--

-- --------------------------------------------------------

--
-- Table structure for table `college`
--

CREATE TABLE `college` (
  `cid` int(3) NOT NULL,
  `college_name` text NOT NULL,
  `coll_city` char(60) NOT NULL,
  `degree` varchar(60) NOT NULL,
  `exams_req` varchar(60) NOT NULL,
  `coll_duration` varchar(200) NOT NULL,
  `recog` varchar(200) NOT NULL,
  `fees` varchar(50) NOT NULL,
  `courses` text NOT NULL,
  `keyword` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `college`
--

INSERT INTO `college` (`cid`, `college_name`, `coll_city`, `degree`, `exams_req`, `coll_duration`, `recog`, `fees`, `courses`, `keyword`) VALUES
(1, 'Impact College of Engineering and Applied Sciences (ICEAS), Sahakara Nagar, Bangalore', 'Bangalore', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Computer science& engineering', 'impact college of engineering and applied sciences (iceas), sahakara nagar, bangalore ,gate ,india ,mtech'),
(2, 'Wisdom School of Management, Indiranagar, Bangalore', 'Bangalore', 'mtech', '-', '2 Years, Correspondence, Post Graduate Degree', 'AICTE Approved,UGC Recognised,DCE Approved', '', 'M.Tech in Mechanical Engineering (Production, Thermal),\nM.Tech in Electrical & Electronics Engineering (Power System, Power Electronics, Control system),\nM.Tech in Electronics & Comm. Engineering (Embedded System & VLSI, Digital Communication,\nM.Tech in Civil Engineering (Highway engg. , Construction Tech. Mgmt, Structural engg.),\nM.Tech in Computer Science	M.Tech in Information Technology\n', 'wisdom school of management, indiranagar, bangalore ,gate ,india ,mtech'),
(3, 'SLN Correspondence College: Karnataka State Open University – Study Centre, Jayanagar, Bangalore', 'Bangalore', 'mtech', '-', '2 Years, Full Time, Post Graduate Degree', 'UGC Recognised, DCE Approved', '', 'IT Engineering ,\r\nElectronics & Comm. Engineering \r\nCivil Engineering ,\r\nElectrical Engineering \r\n', 'sln correspondence college: karnataka state open university – study centre, jayanagar, bangalore , gate ,  india ,mtech'),
(4, 'Sambhram Institute of Technology (SAIT Bangalore), Jalahalli, Bangalore', 'Bangalore', 'mtech', 'GATE,PGCET 			 		', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Civil engineering,\r\nMechanical engineering\r\nComputer science & engineering\r\n\r\n', 'sambhram institute of technology (sait bangalore), jalahalli, bangalore , gate ,india ,mtech'),
(5, 'Atria Institute of Technology, Anand Nagar, Bangalore', 'Bangalore', 'mtech', 'PGCET,GATE ', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Computer science& engineering', 'atria institute of technology, anand nagar, bangalore , gate ,india ,mtech'),
(6, 'Mysore Correspondence College, Malleswaram, Bangalore', 'Bangalore', 'mtech', '-', '2 Years, Correspondence, Post Graduate Degree', '', '', 'I.T.', 'mysore correspondence college, malleswaram, bangalore , gate ,india ,mtech'),
(7, 'Techno India University, Salt Lake City, Kolkata', 'Kolkata', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', '', '', 'Mechanical,\r\nE&T ,\r\nCIVIL,\r\nElectrical,\r\nComputer science &engineering\r\n', 'techno india university, salt lake city, kolkata, gate ,india ,mtech'),
(8, 'Jadavpur University (JU, Kolkata), Jadavpur, Kolkata', 'Kolkata', 'mtech', 'GATE ', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Electrical ,\r\nMechanical ,\r\nE&T ,\r\nIT.', 'jadavpur university (ju, kolkata), jadavpur, kolkata , gate ,india ,mtech'),
(9, 'JIS College of Engineering (JISCE), Kalyani, KoLKATA', 'Kolkata', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'MECHANICAL ,\r\nComputer science& engineering\r\n\r\n', 'jis college of engineering (jisce), kalyani, kolkata , gate ,india ,mtech'),
(10, 'Narula Institute of Technology (NIT, Agarpara)', 'Kolkata', 'mtech', 'GATE', ' 2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'E&t engineering\r\nComputer science& engineering\r\nCivil engineering\r\nElectrical engineering\r\n', 'narula institute of technology (nit, agarpara), kolkata , gate ,india ,mtech'),
(11, 'MCKV Institute of Engineering, Liluah, Kolkata', 'Kolkata', 'mtech', '-', '2 Years, Full Time, Post Graduate Degree	', '', '', 'Computer science & engineering\r\nE&T engineering', 'mckv institute of engineering, liluah, kolkata ,india ,mtech'),
(12, 'Amity University, Kolkata, Kadampukur, Kolkata', 'Kolkata', 'mtech', '', '', 'UGC Recognised', '', 'Computer science engineering,\r\nE&T engineering,\r\nMechanical engineering', 'amity university, kolkata, kadampukur  ,india ,mtech'),
(13, 'Dr. Sudhir Chandra Sur Degree Engineering College (DSCSDEC), Dum Dum, Kolkata', 'Kolkata', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree	', 'AICTE Approved', '', 'Mechanical engineering\r\n', 'dr. sudhir chandra sur degree engineering college (dscsdec), dum dum, kolkata ,india ,mtech'),
(14, 'Brainware Group of Institutions, Barasat, Kolkata', 'Kolkata', 'mtech', 'GATE,PGCET ', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'E&T engineering', 'brainware group of institutions, barasat, kolkata, gate,pgcet,india ,mtech'),
(15, 'Techno India College of Technology (TICT), Rajarhat, Kolkata', 'Kolkata', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree	', 'AICTE Approved', '', 'ELECTRICAL ENGINEERING', 'techno india college of technology (tict), rajarhat, kolkata, gate,pgcet,india ,mtech'),
(16, 'BRIGHT TECHNO, Birati, Kolkata', 'Kolkata', 'mtech', '', '2 Years, Correspondence, Post Graduate Degree', 'DEC Approved', '', '', 'bright techno, birati, kolkata,india ,mtech'),
(17, 'Dream Institute of Technology (DIT, Kolkata), Thakurpukur, Kolkata', 'Kolkata', 'mtech', '', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', '', 'dream institute of technology (dit, kolkata), thakurpukur, kolkata,india ,mtech'),
(18, 'Institute of Engineering and Management, Salt Lake City, Kolkata', 'Kolkata', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', '', 'institute of engineering and management, salt lake city, kolkata, gate , india , mtech'),
(19, 'University of Engineering and Management, Kolkata, Rajarhat, Kolkata', 'Kolkata', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'UGC Recognised', '', '', 'university of engineering and management, kolkata, rajarhat, kolkata, gate , india , mtech'),
(20, 'EIMT Educate, Gariahat Road, Kolkata', 'Kolkata', 'mtech', '', ' 2 Years, Correspondence, Post Graduate Degree', '', '', '', 'eimt educate, gariahat road, kolkata   , india , mtech'),
(21, 'Government College of Engineering and Ceramic Technology, A.J.C. Bose Road, Kolkata', 'Kolkata', 'mtech', '', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', '', 'government college of engineering and ceramic technology, a.j.c. bose road, kolkata, india , mtech'),
(22, 'Larn Edutech, Behala, Kolkata', 'Kolkata', 'mtech', '', '2 Years, Correspondence, Post Graduate Degree', 'AICTE Approved, UGC Recognised, DEC Approved', '', '', 'larn edutech, behala, kolkata, india , mtech'),
(23, 'Krishna Distance Education Centre PVT. LTD, Salt Lake Sector 1, Kolkata', 'Kolkata', 'mtech', '', '2 Years, Correspondence, Post Graduate Degree', 'AICTE Approved, UGC Recognised', '', '', 'krishna distance education centre pvt. ltd, salt lake sector 1, kolkata  , india , mtech'),
(24, ' A S Educare Institute, Rajbari, Kolkata', 'Kolkata', 'mtech', '', '2 Years, Correspondence, Post Graduate Degree', '', '', '', 'a s educare institute, rajbari, kolkata, india , mtech'),
(25, 'RCC Institute of Information Technology (RCCIIT), Beliaghata, Kolkata', 'Kolkata', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', '', 'rcc institute of information technology (rcciit), beliaghata, kolkata , gate , india , mtech'),
(26, 'Government College of Engineering and Ceramic Technology (GCECT), Salt Lake City, Kolkata', 'Kolkata', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', '', 'government college of engineering and ceramic technology (gcect), salt lake city, kolkata , gate , india , mtech'),
(27, 'Department of Jute and Fibre Technology - Institute of Jute Technology, Calcutta University, Ballygu', 'Kolkata', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', '', 'department of jute and fibre technology - institute of jute technology, calcutta university, ballygu , kolkata , gate , india , mtech'),
(28, 'Veermata Jijabai Technological Institute, Mumbai', 'Mumbai', 'mtech', 'GATE', '2 years', 'AICTE recognised', '1.6 Lakh', 'Civil Engineering ( with Specialization in Environmental Engineering )\r\n\r\n\r\n\r\n\r\nCivil Engineering (with Specialization in Construction Management) \r\n\r\n\r\n\r\n\r\nCivil Engineering (with Specialization in Structural Engineering)\r\n\r\n\r\n\r\n\r\nComputer Engineering\r\n\r\n\r\nElectrical Engineering (with specialization in Power Systems)\r\n\r\n\r\nElectrical Engineering (with specialization in Control Systems)\r\n\r\n\r\n\r\n\r\nElectronics Engineering\r\n\r\n\r\n\r\n\r\nMechanical Engineering (with specialization in Machine Design)\r\n\r\n\r\n\r\n\r\nMechanical Engineering (with specialization in Automobile  \r\n\r\nEngineering )\r\n\r\n\r\n\r\n\r\n\r\nMechanical Engineering (with specialization CAD/CAM & Automation) ', ''),
(29, 'Sardar Patel College of Engineering, Andheri West, Mumbai\n\n', 'Mumbai', 'mtech', 'GATE', '2 years', 'AICTE recognised', 'INR 60,500 ', 'CIVIL \r\nMECHANICAL\r\nELECTRICAL\r\n', ''),
(30, 'Indian Institute of Technology (IIT), Mumbai\r\n\r\n', 'Mumbai', 'mtech', 'GATE', '2 years', 'AICTE recognised', 'INR 75,000 ', 'Master of Technology in Mechanical Engineering\r\n\r\nMaster of Technology in Electrical Engineering\r\n\r\nMaster of Technology in Civil Engineering\r\n\r\n', ''),
(31, 'Mukesh Patel School of Technology Management & Engineering\r\n', 'Mumbai', 'mtech', 'GATE', '2 years', 'AICTE recognised', 'INR 3.0 Lakh ', 'Master of Computer Applications\r\nMaster of Technology in Electronics Engineering	\r\nMaster of Technology in Information Technology\r\nmaster of electronic and telecommunication\r\n', ''),
(32, 'Indira College of Engineering and Management (ICEM), Parandwadi, Pune', 'pune', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', '', 'indira college of engineering and management (icem), parandwadi, pune, gate , india , mtech'),
(33, 'DY Patil School of Engineering, Lohegaon, Pune', 'pune', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', ' AICTE Approved', '', 'Computer engineering,\r\nMechanical engineering ,\r\nE&T engineering', 'dy patil school of engineering, lohegaon, pune, gate , india , mtech'),
(34, 'Wisdom School of Management, Hadapsar, Pune', 'pune', 'mtech', '', '', '', '', '', 'wisdom school of management, hadapsar, pune , india , mtech'),
(35, 'Marathwada Mitra Mandal''s College of Engineering (MMCOE)', 'pune', 'mtech', 'GATE', '', 'AICTE Approved', '', 'Computer engineering', 'marathwada mitra mandal''s college of engineering (mmcoe) , pune     , gate , india , mtech'),
(36, 'Sudarshan College of Management Research and Engineering, Bibwewadi, Pune', 'pune', 'mtech', '', '', '', '', 'Computer engineering,\r\n    Mechanical engineering,\r\n    IT engineering,\r\n    E& T engineering ,\r\n    Electrical engineering', 'sudarshan college of management research and engineering, bibwewadi, pune, india , mtech'),
(37, 'Symbiosis Institute of Technology (SIT), Lavale Village, Pune', 'pune', 'mtech', '', '', '', '', '', 'symbiosis institute of technology (sit), lavale village, pune, india , mtech'),
(38, 'Trinity Academy of Engineering, Kondhwa, Pune', 'pune', 'mtech', 'GATE', '', 'AICTE Approved, UGC Recognised', '', 'Mechanical engineering', 'trinity academy of engineering, kondhwa, pune, gate , india , mtech'),
(39, 'KJ''s Educational Institute, Kondhwa, Pune', 'pune', 'mtech', '', '', 'AICTE Approved', '', '', 'kj''s educational institute, kondhwa, pune, india , mtech'),
(40, 'Institute of Knowledge College of Engineering, Hadapsar, Pune', 'pune', 'mtech', '', '', 'AICTE Approved', '', 'Computer engineering', 'institute of knowledge college of engineering, hadapsar, pune, india , mtech'),
(41, 'Cummins College of Engineering for Women (CCOEW), Karve Nagar, Pune', 'pune', 'mtech', 'GATE', '', 'AICTE Approved', '', 'Computer engineering', 'cummins college of engineering for women (ccoew), karve nagar, pune, gate , india , mtech'),
(42, 'Bharati Vidyapeeth Deemed University College of Engineering (BVUCOE)', 'pune', 'mtech', 'GATE', '', 'AICTE Approved', '', '', 'bharati vidyapeeth deemed university college of engineering (bvucoe), pune, gate , india , mtech'),
(43, 'College of Engineering Pune (CoEP), Shivaji Nagar, Pune', 'pune', 'mtech', 'GATE', '', 'AICTE Approved', '', '', 'college of engineering pune (coep), shivaji nagar, pune, gate , india , mtech'),
(44, 'Pune Institute, B S Dhole Patil Path, Pune', 'pune', 'mtech', '', '', '', '', '', 'pune institute, b s dhole patil path, pune, india , mtech'),
(45, 'G H Raisoni College of Engineering & Management, Pune, Wagholi, Pune', 'pune', 'mtech', 'GATE', '', 'AICTE Approved', '', 'Computer engineering,\r\nMechanical engineering\r\n', 'g h raisoni college of engineering & management, pune, wagholi, pune, gate , india , mtech'),
(46, 'Vishwakarma Institute of Technology (VIT, Pune)', 'pune', 'mtech', 'GATE', '', 'AICTE Approved', '', 'Computer engineering,\r\nE& T engineering\r\n', 'vishwakarma institute of technology (vit, pune), pune, gate , india , mtech'),
(47, 'K J College of Engineering & Management Research (KJCOEMR)', 'pune', 'mtech', 'GATE', '', 'AICTE Approved', '', 'Computer engineering', 'k j college of engineering & management research (kjcoemr), pune, gate , india , mtech'),
(48, 'Wisdom School of Management, Mandaveli Rd., Chennai', 'Chennai', 'mtech', '-', '2 Years, Correspondence, Post Graduate Degree', 'AICTE Approved, UGC Recognised, DEC Approved', '', '', 'wisdom school of management, mandaveli rd., chennai , india , mtech'),
(49, 'SRM University, Chennai (SRM Chennai), Kattankulathur, Chennai', 'Chennai', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'UGC Recognised', '', 'COMPUTER SCIENCE & ENGINEERING\r\n', 'srm university, chennai (srm chennai), kattankulathur, chennai , gate , india , mtech'),
(50, 'B.S. Abdur Rahman University (BSAU), Vandalur, Chennai', 'Chennai', 'mtech', '-', '2 Years, Full Time, Post Graduate Degree', 'UGC Recognised', '', 'M.Tech in Information Technology,\r\nM.Tech in Computer Science and Engineering', 'b.s. abdur rahman university (bsau), vandalur, chennai , india , mtech'),
(51, 'Hindustan University (HU, Chennai), Kelambakkam, Chennai', 'Chennai', 'mtech', '-', '2 Years, Full Time, Post Graduate Degree', 'UGC Recognised', '', '\r\nM.Tech in Computer Science and Engineering, \r\nM.Tech in Electrical and Electronics Engineering,\r\nM.Tech in Electronics and Communication Engineering, \r\nM.Tech in Civil Engineering', 'hindustan university (hu, chennai), kelambakkam, chennai, india , mtech'),
(52, 'Saveetha University - Thandalam, Thandalam, Chennai', 'Chennai', 'mtech', '-', '2 Years, Full Time, Post Graduate Degree', '', '', 'Computer engineering,\r\nI.T.', 'saveetha university - thandalam, thandalam, chennai, india , mtech'),
(53, 'Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya (SCSVMV), Kanchipuram, Chennai', 'Chennai', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'UGC Recognised', '', 'Information Technology', 'sri chandrasekharendra saraswathi viswa mahavidyalaya (scsvmv), kanchipuram , chennai , gate , india , mtech'),
(54, 'Anna University (AU Chennai), Guindy, Chennai', 'Chennai', 'mtech', 'TANCET', '2 Years, Full Time, Post Graduate Degree', '', '', 'Information Technology', ' anna university (au chennai), guindy, chennai , tancet , india , mtech'),
(55, 'Vel Tech Dr.RR and Dr.SR Technical University (VelTech, VTU), Avadi, Chennai', 'Chennai', 'mtech', 'VTUEEE', '3 Years, Part Time, Post Graduate Degree', 'UGC Recognised', '', 'Computer science & engineering ,\r\nI.T. engineering .', 'vel tech dr.rr and dr.sr technical university (veltech, vtu), avadi, chennai, vtueee , india , mtech'),
(56, 'Sathyabama University, Jeppiaar Nagar, Chennai', 'Chennai', 'mtech', '-', '2 Years, Full Time, Post Graduate Degree', '', '', 'Information Technology', 'sathyabama university, jeppiaar nagar, chennai, india , mtech'),
(57, 'SSN College of Engineering (SSNCE), Okkiyam Thuraipakkam, Chennai', 'Chennai', 'mtech', 'GATE,TANCET', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Information Technology', ' ssn college of engineering (ssnce), okkiyam thuraipakkam, chennai , tancet , gate , india , mtech'),
(58, 'RRASE College of Engineering, Padappai, Chennai', 'Chennai', 'mtech', '-', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'COMPUTER SCIENCE& ENGINEERING', 'rrase college of engineering, padappai, chennai , india , mtech'),
(59, 'Meenakshi College of Engineering (MCE, Chennai), K.K Nagar, Chennai', 'Chennai', 'mtech', 'TANCET', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'COMPUTER SCIENCE & ENGINEERING', ' meenakshi college of engineering (mce, chennai), k.k nagar, chennai, tancet  , india , mtech'),
(60, 'Bharath University (BU, Chennai), Selaiyur, Chennai', 'Chennai', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'UGC Recognised', '', 'COMPUTER SCIENCE& ENGINEERING,\r\nIT engineering', 'bharath university (bu, chennai), selaiyur, chennai, gate , india , mtech'),
(61, 'R&R Education Foundation, Rani Bagh, Delhi', 'Delhi', 'mtech', '-', '2 Years, Correspondence, Post Graduate Degree', '', '', '\r\nM.Tech in Civil Engineering, \r\nM.Tech in Mechanical Engineering,\r\nM.Tech in Electrical Engineering, \r\nM.Tech in Information and Technology,\r\nM.Tech in Computer Science and Engineering', 'r&r education foundation, rani bagh, delhi , india , mtech'),
(62, 'Lovely Professional University - Admission Office, Connaught Place, Delhi', 'Delhi', 'mtech', 'GATE,LPU-NEST', '2 Years, Full Time, Post Graduate Degree', 'UGC Recognised', '', 'M.Tech in Information Technology,\r\nM.Tech in Mechanical Engineering, \r\nM.Tech in Electronics and Communication Engineering, \r\nM.Tech in Computer Science and Engineering, s\r\nM.Tech in Civil Engineering, \r\nM.Tech in electrical engineering\r\n', 'lovely professional university - admission office, connaught place, delhi ,  lpu-nest ,  gate , india , mtech'),
(63, 'Ganga Group of Institutions- Ganga Institute of Technology & Management, Punjabi Bagh, Delhi', 'Delhi', 'mtech', '-', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Computer science & engineering,\r\nE&T engineering', 'ganga group of institutions- ganga institute of technology & management, punjabi bagh, delhi, india , mtech'),
(64, 'GLA University (Admission Office), New Friends Colony, Delhi', 'Delhi', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'UGC Recognised', '', '	\r\n M.Tech in Mechanical Engineering, \r\n  M.Tech in Computer Science and Engineering, \r\n M.Tech in Electronics and Communication Engineering,\r\n M.Tech in Civil Engineering, \r\n M.Tech in Electrical Engineering.', 'gla university (admission office), new friends colony, delhi,  gate , india , mtech'),
(65, 'Incline Institute of IT and Management, Dwarka, Delhi', 'Delhi', 'mtech', '-', '2 Years, Part Time, Post Graduate Degree', 'AICTE Approved, UGC Recognized', '', 'Mechanical engineering,\r\nElectrical engineering,\r\nElectronics engineering', 'incline institute of it and management, dwarka, delhi , india , mtech'),
(66, 'Delhi College of Advanced Studies, Janakpuri, Delhi', 'Delhi', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', '', '', 'Computer science ', 'delhi college of advanced studies, janakpuri, delhi, india , mtech'),
(67, 'APL Institute Of IT And Management Studies, Uttam Nagar, Delhi', 'Delhi', 'mtech', '-', '2 Years, Part Time, Post Graduate Degree', 'AICTE Approved, UGC Recognised', '', 'Electrical engineering,\r\nElectronics engineering', 'apl institute of it and management studies, uttam nagar, delhi , india , mtech'),
(68, 'Noble Institute of Professional Studies (NIPS Delhi), Delhi', 'Delhi', 'mtech', 'GATE', '2 Years, Correspondence, Post Graduate Degree', 'UGC Recognized, DEC Approved', '', 'Information Technology', 'noble institute of professional studies (nips delhi), delhi, india , mtech'),
(69, 'Ambition Institute of Education, Vikas Puri, Delhi', 'Delhi', 'mtech', '', '2 Years, Correspondence, Post Graduate Degree', 'UGC Recognized, DEC Approved', '', 'Mechanical engineering,\r\nCivil engineering,\r\nElectrical engineering,\r\nElectronics engineering,\r\nIT engineering,\r\nComputer engineering', 'ambition institute of education, vikas puri , delhi, india , mtech'),
(70, 'Disha College of Education, Najafgarh, Delhi', 'Delhi', 'mtech', '', '', '', '', 'Civil Engineering,\r\nMechanical Engineering,\r\nElectrical Engineering,\r\nI.T Engineering,\r\nElectronics and Communications Engineering,\r\nComputer Science & Engineering.', 'disha college of education, najafgarh, delhi , india , mtech'),
(71, 'Navodaya Education, Uttam Nagar, Delhi', 'Delhi', 'mtech', '', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved, UGC Recognised, DEC Approved', '', 'Civil engineering', 'navodaya education, uttam nagar, delhi, india , mtech'),
(72, 'Chanderprabhu Jain Institute of Management & Technology, Anand Vihar, Delhi', 'Delhi', 'mtech', '', '2 Years, Full Time, Post Graduate Degree', '', '', ' Computer Science,\r\nInformation Technology,\r\nElectronics and Telecommunication,\r\nMechanical,\r\nCivil,\r\nElectrical Engineering.', 'chanderprabhu jain institute of management & technology, anand vihar, delhi, india , mtech'),
(73, 'Aryabhatta Degree College (ADC Tughlakabad), Tughlakabad, Delhi', 'Delhi', 'mtech', '', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved, UGC Recognised', '', 'M.Tech  in Chemical,\r\nM.Tech  in  Mechanical\r\nM.Tech  in IT, \r\nM.Tech  in  Computer Science,\r\nM.Tech  in  Electronics,\r\n M.Tech  in  Electrical ', 'aryabhatta degree college (adc tughlakabad), tughlakabad, delhi, india , mtech'),
(74, 'Guru Gobind Singh Indraprastha University (GGSIP), Dwarka, Delhi', 'Delhi', 'mtech', 'GATE,GGSIPU', '2 Years, Full Time, Post Graduate Degree', 'UGC Recognised', '', 'M.Tech in Electronics and Communication Engineering,\r\nM.Tech in Computer Science and Engineering,\r\nM.Tech in Information Technology.\r\n', 'guru gobind singh indraprastha university (ggsip), dwarka, delhi,  gate , ggsipu , india , mtech'),
(75, 'Maharaja Agrasen Institute of Technology, Delhi', 'Delhi', 'mtech', '', '2 Years, Full Time, Post Graduate Degree', '', '', 'Information Technology.', 'maharaja agrasen institute of technology, delhi, india , mtech'),
(76, 'Heights Institute, Nangloi, Delhi', 'Delhi', 'mtech', '', '', '', '', 'ELECTRICAL ENGINEERING,\r\nIT engineering,\r\nCivil engineering.', 'heights institute, nangloi, delhi, india , mtech'),
(77, 'DIT University (Admission Office), East Of Kailash, Delhi', 'Delhi', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'UGC Recognised', '', 'Mechanical engineering,\r\n	Computer science & engineering,\r\n	Civil engineering,\r\n	Electrical engineering,\r\n	E&T engineering.\r\n', 'dit university (admission office), east of kailash, delhi,  gate , india , mtech'),
(78, 'Saroj Educational Group, Lajpat Nagar, Delhi', 'Delhi', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'COMPUTER SCIENCE,\r\nE& T ENGINEERING.', 'saroj educational group, lajpat nagar, delhi,  gate , india , mtech'),
(79, 'Pratham Institute of Education, Lajpat Nagar, Delhi', 'Delhi', 'mtech', '', '2 Years, Correspondence, Post Graduate Degree', '', '', 'Telecommunications ,\r\nComputer Science (IT)\r\n,Electronics\r\n,Mechanical  \r\n,Electronics & Telecommunication\r\n,Civil\r\n,Electrical.\r\n', 'pratham institute of education, lajpat nagar, delhi, india , mtech'),
(80, 'Wisdom School of Management, Kalyan East, Mumbai', 'Mumbai', 'mtech', '', '', 'AICTE Approved, UGC Recognised, DEC Approved', '', 'Mechanical engineering,\r\nIT engineering,\r\nElectrical engineering,\r\nE&T engineering.\r\n', 'wisdom school of management, kalyan east, mumbai, india , mtech'),
(81, 'NMIMS University''s Mukesh Patel School of Technology Management and Engineering, Vile Parle , mumbai', 'Mumbai', 'mtech', 'GATE', '', '', '', 'Computer engineering,\r\nE&T engineering.', 'nmims university''s mukesh patel school of technology management and engineering, vile parle , mumbai,  gate , india , mtech'),
(82, 'International Institute of Management and Engineering, Mira Road, Mumbai', 'Mumbai', 'mtech', '', '2 Years, Correspondence, Post Graduate Degree', '', '', '', 'international institute of management and engineering, mira road, mumbai , india , mtech'),
(83, 'National Education Management, Mumbai, Mumbai', 'Mumbai', 'mtech', '', '', '', '', 'Mechanical engineering,\r\nElectronics engineering,\r\nElctronics & telecommunication ', 'national education management, mumbai, mumbai, india , mtech'),
(84, 'National Institute of Management, Malad West, Mumbai', 'Mumbai', 'mtech', '', '2 Years, Correspondence, Post Graduate Degree', '', '', 'Mechanical engineering,\r\nElectronics engineering.', 'national institute of management, malad west, mumbai, india , mtech'),
(85, ' JRD Global Education, thane, Mumbai', 'Mumbai', 'mtech', '', '3 Years, Correspondence, Dual Degree ', '', '', '', 'jrd global education, thane, mumbai, india , mtech'),
(86, 'YES Education, Mulund West, Mumbai', 'Mumbai', 'mtech', '', '', 'UGC Recognised', '', '', 'yes education, mulund west, mumbai, india , mtech'),
(87, 'Kanwal Rekhi School of Information Technology, IIT Powai, Mumbai', 'Mumbai', 'mtech', '', '2 Years, Full Time, Post Graduate Degree', '', '', '', 'kanwal rekhi school of information technology, iit powai, mumbai, india , mtech'),
(88, 'Alamuri Ratnamala Institute of Engineering and Technology (ARMIET)', 'Mumbai', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Mechanical engineering\r\nComputer engineering\r\ne&t engineering', 'alamuri ratnamala institute of engineering and technology (armiet)parle , mumbai,  gate , india , mtech'),
(89, 'Institute for Development and Research in Banking Technology, Hyderabad', 'Hyderabad', 'mtech', '', '2 Years, Full Time, Post Graduate Degree', '', '', 'Information technology', 'institute for development and research in banking technology, hyderabad, india , mtech'),
(90, 'Shadan College of Engineering and Technology, Himayat Nagar, Hyderabad', 'Hyderabad', 'mtech', '', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Computer & science engineering', 'shadan college of engineering and technology, himayat nagar, hyderabad, india , mtech'),
(91, 'CMR Technical Campus (CMRTC), Medchal, Hyderabad', 'Hyderabad', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Computer science & engineering\r\n', 'cmr technical campus (cmrtc), medchal, hyderabad ,  gate , india , mtech'),
(92, 'Moghal College of Engineering and Technology (MCET), Chandrayanagutta, Hyderabad', 'Hyderabad', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', '', 'moghal college of engineering and technology (mcet), chandrayanagutta, hyderabad,  gate , india , mtech'),
(93, 'Keshav Memorial Institute of Technology, Narayanguda, Hyderabad', 'Hyderabad', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Computer science & engineering', 'keshav memorial institute of technology, narayanguda, hyderabad,  gate , india , mtech'),
(94, 'Joginpalli B.R.Engineering College, Moinabad, Hyderabad', 'Hyderabad', 'mtech', '-', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Computer Science and Engineering ,\r\nInformation Technology ,\r\nElectronics and Communication Engineering  ,\r\nElectrical and Electronics Engineering (PE&ED).\r\n', 'joginpalli b.r.engineering college, moinabad, hyderabad, india , mtech'),
(95, 'Deccan College of Engineering and Technology, Nampalli, Hyderabad', 'Hyderabad', 'mtech', 'GATE', '4 Years, Full Time, Post Graduate Degree', '', '', 'Computer science& engineering', 'deccan college of engineering and technology, nampalli, hyderabad,  gate , india , mtech'),
(96, 'Sridevi Women''s Engineering College, Begumpet, Hyderabad', 'Hyderabad', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Computer science& engineering,\r\nElectrical   & electronics engineering.\r\n', 'sridevi women''s engineering college, begumpet, hyderabad,  gate , india , mtech'),
(97, 'SV Group of institute, Moinabad, Hyderabad', 'Hyderabad', 'mtech', '-', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Computer science & engineering,\r\nElectronics & telecommunication engineering.\r\n', 'sv group of institute, moinabad, hyderabad, india , mtech'),
(98, 'Sphoorthy Engineering College, Saroornagar, Hyderabad', 'Hyderabad', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Computer science&  engineering,\r\nE&T engineering.\r\n', 'sphoorthy engineering college, saroornagar, hyderabad,  gate , india , mtech'),
(99, 'University of Hyderabad, Gachibowli, Hyderabad', 'Hyderabad', 'mtech', '-', '2 Years, Full Time, Post Graduate Degree', '', '', 'IT engineering,\r\nComputer engineering.', 'university of hyderabad, gachibowli, hyderabad, india , mtech'),
(100, 'Osmania University, Tarnaka, Hyderabad', 'Hyderabad', 'mtech', '-', '2 Years, Full Time, Post Graduate Degree', 'UGC Recognised', '', 'Computer science& engineering', 'osmania university, tarnaka, hyderabad, india , mtech'),
(101, 'Jawaharlal Nehru Technological University, Hyderabad', 'Hyderabad', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'UGC Recognised', '', 'Computer engineering', 'jawaharlal nehru technological university, hyderabad,  gate , india , mtech'),
(102, 'Wisdom School of Management, Banjara Hills, Hyderabad', 'Hyderabad', 'mtech', '', '', '', '', 'M.Tech in Mechanical Engineering (Production, Thermal)\r\n,M.Tech in Electrical & Electronics Engineering (Power System, Power Electronics, Control system),\r\nM.Tech in Electronics & Comm. Engineering (Embedded System & VLSI, Digital Communication,\r\nM.Tech in Civil Engineering (Highway engg. , Construction Tech. Mgmt, Structural engg.),\r\nM.Tech in Computer Science and\r\nM.Tech in IT.\r\n\r\n\r\n', 'wisdom school of management, banjara hills, hyderabad , india , mtech'),
(103, 'Lords Institute of Engineering & Technology, Himayathsagar, Hyderabad', 'Hyderabad', 'mtech', 'PGECET', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Computer science& engineering', 'lords institute of engineering & technology, himayathsagar, hyderabad ,  pgecet  , india , mtech'),
(104, 'Annamacharya Institute of Technology and Sciences (AITS), Hayat Nagar, Hyderabad', 'Hyderabad', 'mtech', '', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Computer science & engineering,\r\nE& T engineering.\r\n', 'annamacharya institute of technology and sciences (aits), hayat nagar, hyderabad, india , mtech'),
(105, 'St. Mary''s Group of Institutions, Ramoji Film City, Hyderabad', 'Hyderabad', 'mtech', '', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Computer science & engineering,\r\nE&T engineering.\r\n', 'st. mary''s group of institutions, ramoji film city, hyderabad, india , mtech'),
(106, 'Shivani College of IT and Management, Dilsukh Nagar, Hyderabad', 'Hyderabad', 'mtech', '', '2 Years, Correspondence, Post Graduate Degree', '', '', 'Civil,\r\nElectrical,\r\nElectronics and Communication,\r\nMechanical and\r\nComputer Science .', 'shivani college of it and management, dilsukh nagar, hyderabad, india , mtech'),
(107, 'Indore Institute of Science and Technology, Indore', 'Indore', 'mtech', '', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Computer science & engineering', 'indore institute of science and technology, indore, india , mtech'),
(108, 'Medi-Caps University, Indore', 'Indore', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'M.Tech in Computer Science, \r\nM.Tech in Electronics and Communication Engineering, \r\nM.Tech in Information Technology, \r\nM.Tech in Mechanical Engineering.', 'medi-caps university, indore,  gate , india , mtech'),
(109, 'Acropolis Technical Campus (ATC Indore), Indore', 'Indore', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Computer science & engineering\r\n', 'acropolis technical campus (atc indore), indore,  gate , india , mtech'),
(110, 'International Institute of Professional Studies (IIPS, Indore), Indore', 'Indore', 'mtech', 'GATE', '66 Months, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Information Technology ', 'international institute of professional studies (iips, indore), indore, india , mtech'),
(111, 'Vikrant Group of Institutions, Indore', 'Indore', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Computer science & engineering,\r\nE&T engineering.', 'vikrant group of institutions, indore,  gate , india , mtech'),
(112, 'Indian Institute of Technology, (IIT Indore), Indore', 'Indore', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', '', '', 'Mechanical engineering,\r\nElectrical engineering.', 'indian institute of technology, (iit indore), indore,  gate , india , mtech'),
(113, 'Acropolis Institute of Technology and Research (AITR), Indore', 'Indore', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Computer science & engineering\r\n', 'acropolis institute of technology and research (aitr), indore,  gate , india , mtech'),
(114, 'Sanghvi Institute of Management and Science(SIMS - INDORE), Indore', 'Indore', 'mtech', '-', '2 Years, Full Time, Post Graduate Degree', '', '', 'Computer science& engineering,\r\nElectronics & communication.', 'sanghvi institute of management and science(sims - indore), indore, india , mtech'),
(115, 'Malwa Institute of Technology (MIT Indore), Indore', 'Indore', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', '', '', 'Mechanical engineering,\r\nCivil engineering,\r\nComputer science & engineering.\r\n', 'malwa institute of technology (mit indore), indore,  gate , india , mtech'),
(116, 'Sri Aurobindo Institute of Technology (SAIT, Indore), Indore', 'Indore', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Mechanical Engineering ,\r\nComputer Science and Engineering .\r\n', 'sri aurobindo institute of technology (sait, indore), indore, india , mtech'),
(117, 'Astral Institute of Technology and Research (Astral, Indore), Indore', 'Indore', 'mtech', '-', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Computer science\r\n', 'astral institute of technology and research (astral, indore), indore, india , mtech'),
(118, 'BM College of Technology (BMCT, Indore), Indore', 'Indore', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Computer science & engineering,\r\nMechanical engineering.', 'bm college of technology (bmct, indore), indore,  gate , india , mtech'),
(119, 'Rishiraj Institute of Technology (RIT, Indore), Indore', 'Indore', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'AICTE Approved', '', 'Computer science & engineering,\r\nE& T  engineering.\r\n', 'rishiraj institute of technology (rit, indore), indore, india , mtech'),
(120, 'Devi Ahilya Vishwavidhyalaya (DAVV), Indore', 'Indore', 'mtech', 'GATE', '2 Years, Full Time, Post Graduate Degree', 'UGC Recognised', '', 'Computer  science,\r\nIT engineering.\r\n', 'devi ahilya vishwavidhyalaya (davv), indore,  gate , india , mtech'),
(121, 'IES Management College and Research Centre', 'Mumbai', 'mba', 'CAT,MAT,CMAT,XAT', '2 years', 'AICTE Approved', 'approx. 7,00,000', 'Post Graduate Diploma in Management,\nMaster of Management Studies,\nPGDM in Pharma and Healthcare Management', 'IES management college and research centre,mba,mumbai,CAT,MAT,CMAT,XAT'),
(122, 'K. J. Somaiya Institute of Management Studies and Research (SIMSR)', 'Mumbai', 'mba', 'CAT,CMAT,XAT,GMAT', '2 years', 'AICTE Approved, UGC Approved', 'approx. 9,48,000', 'Post Graduate Diploma in Management,\r\nMasters in Management Studies,\r\nPG Diploma in Retail Management,\r\nPG Diploma in International Business,\r\nPG Diploma in Financial Services, \r\nPG Diploma in Communications,\r\nPh.D. (Arts) in Management Studies.', 'K. J. Somaiya Institute of Management Studies and Research (SIMSR),SIMSR,mba,mumbai,kj somaiya,CAT,CMAT,XAT,GMAT'),
(123, 'Prin. L. N. Welingkar Institute of Management Development and Research (WeSchool)', 'Mumbai', 'mba', 'CAT,CMAT,XAT,ATMA', '2 years', 'AICTE Approved', 'approx. 8,64,000', 'Post Graduate Diploma in Management,\r\nPGDM in Business Design,\r\nPGDM in E-Business,\r\nPGDM in Retail Management,\r\nPGDM in Rural Management (Emerging Economies),\r\nMaster in Management Studies,\r\nPGDM in Healthcare Management,\r\nPGDM in Media and Entertainment,\r\nPGDM in Research and Business Analytics,', 'L. N. welingkar institute of management development and research (WeSchool),mba,mumbai,cat,cmat,xat,atma,lnwelingkar'),
(124, 'D Y Patil University School of Management (DYPUSM)', 'Mumbai', 'mba', 'CAT,CMAT,MAH-CET', '2 years', 'UGC Approved', 'approx. 5,90,000 ', 'Master of Business Administration,\r\nMBA in Retail Management,\r\nMBA in International Business Management,\r\nMBA in Banking and Insurance,\r\nMBA in Pharmaceutical Industry Management,\r\nMBA in Biotechnology Management,\r\nMBA in Bioinformatics Management,\r\nMBA in Health and Hospital Management,\r\nMBA in Logistics and Supply Chain Management,\r\nMBA in Outsourcing Management,\r\nMBA in Aviation Management.', 'd y patil university school of management (dypusm) , dypusm   , mumbai , mba , cat, cmat ,mah-cet'),
(125, 'Universal Business School (UBS Sion)', 'Mumbai', 'mba', 'CAT,CMAT,MAH-CET,MAT', '', 'AICTE Approved', 'approx. 7,98,000 ', 'Post Graduate Diploma in Management,\r\nMBA + PGDM,\r\nMBA + PGDM + PGPM,\r\nMBA + PGCM,\r\nPGPM + PGCM + Certificate in Digital Marketing,\r\nPost Graduate Program in Management.', 'universal business school (ubs sion)  , ubs sion   , mumbai , mba , cat,cmat,mah-cet,mat'),
(126, 'Durgadevi Saraf Institute of Management Studies (DSIMS)', 'Mumbai', 'mba', 'CAT,MAT,CMAT,XAT', '2 years', 'AICTE Approved', 'approx. 7,80,000 ', 'Post Graduate Diploma in Management,\r\nMaster of Management Studies.', '\r\ndurgadevi saraf institute of management studies (dsims) , dsims  ,  mumbai , mba , cat , mat, cmat, xat \r\n'),
(127, 'International College of Financial Planning, Mumbai (ICOFP)', 'Mumbai', 'mba', 'CAT,MAT,XAT,SN', '2 years', '', 'approx. 5,62,500 ', 'MBA in Financial Planning + Advanced Program in Financial Planning + CFP Certification', 'international college of financial planning, mumbai (icofp) , icofp , mumbai , mba , cat , mat, xat, sn'),
(128, 'BSE Institute Limited, Mumbai', 'Mumbai', 'mba', 'CAT,MAT,CMAT', '2 years', '', '', 'Post Graduate Program in Global Financial Markets,\r\nPost Graduate Program in Banking and Finance,\r\nMaster of Business Administration.', 'bse institute limited, mumbai , mba  , cat , mat , cmat'),
(129, 'Deviprasad Goenka Management College of Media Studies (DGMC)', 'Mumbai', 'mba', ' MAH-CET,CAT,GMAT', '2 years', 'AICTE Approved', 'approx. 5,90,000 ', 'PGDM in Media and Communication,\r\nPost Graduate Diploma in Digital Marketing.', 'deviprasad goenka management college of media studies (dgmc) , dgmc  ,  mumbai  , mba  , mah-cet, cat, gmat'),
(130, 'National Institute of Securities Markets (NISM)', 'Mumbai', 'mba', 'CAT,MAT,CMAT,XAT', '1 Year', '', 'approx. 4,77,000 ', 'Post Graduate Program in Securities Markets,\r\nPost Graduate Diploma in Quantitative Finance.', 'national institute of securities markets (nism) , nism  , mumbai  , mba  , cat, mat , cmat, xat'),
(131, 'ITM Business School, Dombivili', 'Thane', 'mba', 'CAT,MAT,CMAT,XAT', '2 years', 'AICTE Approved', 'approx. 6,31,000 ', 'Post Graduate Diploma in Management.', 'itm business school, dombivili ,  thane , mba  , cat, mat , cmat, xat'),
(132, 'ASM''s Institute of Management and Computer Studies (IMCOST)', 'Thane', 'mba', 'CAT,MAT,CMAT,XAT,MAH-CET', '2 years', 'AICTE Approved', 'approx. 2,60,000 ', 'Masters of Management Studies.', 'asm''s institute of management and computer studies (imcost) , imcost  , thane , mba  , cat , mat , cmat , xat , mah-cet'),
(133, 'ITM Business School, Navi Mumbai (ITM)', 'Mumbai', 'mba', 'CAT,MAT,CMAT,XAT', '2 years', 'AICTE Approved', '11,79,000 ', 'Post Graduate Diploma in Management', 'itm business school, navi mumbai (itm) , itm , mumbai , mba , cat,mat,cmat,xat'),
(134, 'Thakur Institute of Management Studies and Research(TIMSR)', 'Mumbai', 'mba', 'CAT,MAT,CMAT,XAT', '2 years', 'AICTE Approved', 'approx. 6,60,000 ', 'Post Graduate Diploma in Management,\r\nMasters in Management Studies.', 'thakur institute of management studies and research(timsr) , timsr  ,  mumbai , mba ,  cat , mat , cmat , xat'),
(135, 'Athena School of Management', 'Mumbai', 'mba', 'CAT,MAT,XAT,ATMA', '2 years', 'UGC Approved', '12,00,000 ', 'MBA + PGPM', 'athena school of management ,  mumbai , mba ,  cat , mat , xat, atma'),
(136, 'Faculty of Management Studies, Manav Rachna International University', 'Delhi', 'mba', 'CAT,MAT,XAT', '2 years', 'UGC Approved', 'approx. 4,99,000 ', 'Master of Business Administration,\r\nMBA in Healthcare Management (With Fortis),\r\nPh.D. in Management,\r\nMBA in Human Resource Management.', 'faculty of management studies, manav rachna international university , delhi , mba , cat , mat , xat'),
(137, 'Jagannath International Management School (JIMS)', 'Delhi', 'mba', 'CAT,MAT,CMAT,XAT', '2 years', 'AICTE Approved', 'approx. 6,30,000 ', '\r\nPost Graduate Diploma in Management,\r\nPost Graduate Diploma in International Business.', 'jagannath international management school (jims)  , jims  , delhi , mba , cat , mat , cmat , xat'),
(138, 'New Delhi Institute of Management (NDIM)', 'Delhi', 'mba', 'CAT,MAT,CMAT,XAT', '2 years', 'AICTE Approved', 'approx. 7,75,000 ', 'Post Graduate Diploma in Management,\r\nPGDM in Marketing,\r\nPGDM in Finance,\r\nMaster of Business Administration.', 'new delhi institute of management (ndim) , ndim , delhi , mba , cat , mat , cmat , xat'),
(139, 'Jagan Institute of Management Studies (JIMS), Sector-5, Rohini	', 'Delhi', 'mba', 'CAT,MAT,CMAT,XAT', '2 years', 'AICTE Approved', 'approx. 6,30,000 ', 'Post Graduate Diploma in Management,\r\nPost Graduate Diploma in Retail Management,\r\nPost Graduate Diploma in International Business.\r\n', '\r\njagan institute of management studies (jims), sector-5, rohini ,  jims  , delhi , mba , cat , mat , cmat , xat\r\n'),
(140, 'Bharatiya Vidya Bhavan''s Usha and Lakshmi Mittal Institute of Management (BULMIM)', 'Delhi', 'mba', 'CAT,MAT,CMAT,XAT', '2 years', 'AICTE Approved', 'approx. 5,50,000 ', 'Post Graduate Diploma in Management.', 'bharatiya vidya bhavan''s usha and lakshmi mittal institute of management (bulmim),  bulmim ,   delhi , mba , cat , mat , cmat , xat\r\n\r\n'),
(141, 'G.L. Bajaj Institute of Management and Research (GLBIMR)', 'Delhi', 'mba', 'CAT,MAT,CMAT,XAT', '2 years', 'AICTE Approved', 'approx. 5,50,000 ', 'Post Graduate Diploma in Management.', 'g.l. bajaj institute of management and research (glbimr) , glbimr ,    delhi , mba , cat , mat , cmat , xat'),
(142, 'Greater Noida Institute of Technology (GNIOT)', 'Greater Noida', 'mba', 'CAT,MAT,CMAT', '2 years', 'AICTE Approved', 'approx. 2,02,300', 'Master of Business Administration,\r\nMBA (Lateral Entry).', 'greater noida institute of technology (gniot) ,  gniot  , mba ,   greater noida  , cat,mat,cmat '),
(143, 'Accurate Institute of Management and Technology', 'Greater Noida', 'mba', 'CAT,MAT,CMAT,XAT', '2 years', 'AICTE Approved', 'approx. 5,60,000 ', 'Post Graduate Diploma in Management,\r\nMaster of Business Administration.', 'accurate institute of management and technology ,  mba ,   greater noida  ,  cat , mat  , cmat , xat'),
(144, 'Apeejay Institute of Technology - School of Management (AITSM)', 'Greater Noida', 'mba', 'CAT,MAT,CMAT,XAT', '2 years', 'AICTE Approved', 'approx. 2,95,200 ', 'Post Graduate Diploma in Management', 'apeejay institute of technology - school of management (aitsm) , aitsm , mba ,   greater noida  ,  cat , mat  , cmat , xat'),
(145, 'Mangalmay Institute of Management and Technology (MIMT, Greater Noida)', 'Greater Noida', 'mba', 'CAT,MAT,CMAT,XAT', '2 years', 'AICTE Approved', 'approx. 2,40,000 ', 'Master of Business Administration.', 'mangalmay institute of management and technology , mimt  , mba ,   greater noida  ,  cat , mat  , cmat , xat'),
(146, 'Alliance School of Business - Alliance University', 'Bangalore', 'mba', 'CAT,MAT,CMAT,XAT', '2 years', 'UGC Approved', 'approx. 13,50,000 ', 'Master of Business Administration,\r\nPost Graduate Diploma in Management,\r\nPh.D. in Management.', 'alliance school of business - alliance university , bangalore , mba , cat , mat , cmat , xat'),
(147, 'Amrita School of Business - Amrita Vishwa Vidyapeetham (ASB, Bangalore)', 'Bangalore', 'mba', 'CAT,MAT,CMAT,XAT', '2 years', 'UGC Approved', 'approx. 10,03,000 ', 'MBA + MS,\r\nPh.D. in Management.', 'amrita school of business - amrita vishwa vidyapeetham (asb, bangalore) , asb , bangalore , mba , cat , mat , cmat , xat'),
(148, 'AIMS Institutes (AIMS)', 'Bangalore', 'mba', 'CAT,MAT,CMAT,XAT', '2 years', 'AICTE Approved', 'approx. 8,10,000 ', 'Master of Business Administration.', 'aims institutes (aims) , aims , bangalore , mba , cat , mat , cmat , xat'),
(149, 'Acharya Bangalore B-School (ABBS)', 'Bangalore', 'mba', 'CAT,MAT,CMAT,XAT', '2 years', 'AICTE Approved', 'approx. 7,56,000 ', 'Master of Business Administration,\r\nPost Graduate Diploma in Management,\r\nPGDM - Global,\r\nPGDM in Banking, Insurance, Finance and Allied Services,\r\nMaster of Business Administration (Mysore University).', 'acharya bangalore b-school (abbs)  , abbs  , bangalore , mba , cat , mat , cmat , xat'),
(150, 'International School of Management Excellence (ISME, Bangalore)	', 'Bangalore', 'mba', 'CAT,MAT,CMAT,XAT', '2 years', 'AICTE Approved', 'approx. 5,75,000 ', 'Post Graduate Diploma in Management,\r\nPGDM + MBA.', 'international school of management excellence (isme) , isme   , bangalore , mba , cat , mat , cmat , xat'),
(151, 'National School of Business (NSB, Banglore)', 'Bangalore', 'mba', 'MAT,CMAT,XAT', '2 years', 'UGC Approved', 'approx. 4,30,000 ', '', 'national school of business (nsb, banglore) , nsb ,  bangalore , mba  ,  mat , cmat , xat\r\n'),
(152, 'Prin. L. N. Welingkar Institute of Management Development and Research (WeSchool)', 'Bangalore', 'mba', 'MAT,CMAT,CAT', '2 years', 'AICTE Approved', 'approx. 8,64,000 ', 'Post Graduate Diploma in Management,\r\nPGDM in Business Design,\r\nPGDM in E-Business.', 'prin. l. n. welingkar institute of management development and research (weschool)  ,  bangalore , mba  ,  mat , cmat , cat'),
(153, 'Adarsh Institute of Management and Information Technology (AIMIT Chamrajpet)', 'Bangalore', 'mba', 'CAT,MAT,CMAT,XAT', '2 years', 'AICTE Approved', 'approx. 4,50,000 ', 'Master of Business Administration,\r\nPost Graduate Diploma in Management.', 'adarsh institute of management and information technology (aimit chamrajpet)  ,  bangalore  , mba  , cat , mat , cmat , xat'),
(154, 'M. S. Ramaiah University of Applied Sciences (MSRUAS)', 'Bangalore', 'mba', 'CAT,MAT,CMAT,XAT', '2 years', 'UGC Approved', 'approx. 4,43,500 ', 'Master of Business Administration,\r\nMaster of Hospital Administration,\r\nMBA in Innovation and Entrepreneurship,\r\nMBA in Pharma Business Management.', 'm. s. ramaiah university of applied sciences (msruas) , msruas  ,  bangalore  , mba , cat , mat , cmat ,  xat'),
(155, 'ITM Business School, Bangalore', 'Bangalore', 'mba', 'CAT,MAT,CMAT,XAT', '2 years', 'AICTE Approved', 'approx. 6,56,000 ', 'Post Graduate Diploma in Management.', 'itm business school , bangalore ,  mba  , cat , mat , cmat ,  xat'),
(156, 'IIKM Business School, Chennai (IIKM Chennai), Nungambakkam, Chennai\n', 'Chennai', 'mba', 'CAT,MAT,XAT,ATMA,GMAT', '2 years', 'UGC recognized University', '4,85,000 ', 'MBA + PGPM + ERP, 2 Years\r\nMBA in Airline and Airport Management, 2 Years\r\nMBA in Shipping & Logistics, 2 Years\r\n\r\n', 'iikm business school , iikm , chennai , mba,cat , mat , xat , atma , gmat'),
(157, 'Loyola Institute of Business Administration (LIBA), Nungambakkam, Chennai\n', 'Chennai', 'mba', 'CAT,XAT', '2 years', 'AICTE Approved', '10,50,000', 'Post Graduate Diploma in Management, 2 Years\r\n', 'loyola institute of business administration (liba), nungambakkam, chennai , liba , mba , cat , xat'),
(158, 'SSN School of Management (SSN SOM), Old Mahabalipuram Road, Chennai\n', 'Chennai', 'mba', 'CAT,MAT,CMAT,XAT,TANCET MBA', '2 years', 'AICTE Approved', '4,00,000 ', 'Master of Business Administration, 2 Years\r\n', 'ssn school of management (ssn som), old mahabalipuram road, chennai , ssn som , chennai , mba , cat,mat,cmat,xat,tancet mba'),
(159, 'VIT Business School, Chennai, Vandalur Kelambakkam Road, Chennai\r\n', 'Chennai', 'mba', 'CAT,MAT,CMAT,XAT,GMAT', '2 years', 'UGC Approved', '5,98,000 ', 'Master of Business Administration, 2 Years\r\n', 'vit business school, chennai, vandalur kelambakkam road, chennai , mba , cat , mat , cmat , xat , gmat'),
(160, 'Hindustan University (HU, Chennai), Kelambakkam, Chennai\n', 'Chennai', 'mba', 'CAT,MAT,CMAT,XAT', '2 years', 'UGC Approved', '3,74,000 ', 'MBA in Media and Entertainment Management, 2 Years\r\nMBA in Hospital and Healthcare Management, 2 Years\r\nMBA in Family Business and Entrepreneurship, 2 Years\r\nMBA in Hospitality Management, 2 Years\r\nMBA in Aviation Management, 2 Years\r\nMasters of Business Administration, 2 Years\r\nMBA in Defence Technology Management, 2 Years\r\nMBA in Automobile Dealership Management, 2 Years\r\n', 'hindustan university (hu, chennai), kelambakkam, chennai , mba , cat , mat, cmat , xat');
INSERT INTO `college` (`cid`, `college_name`, `coll_city`, `degree`, `exams_req`, `coll_duration`, `recog`, `fees`, `courses`, `keyword`) VALUES
(161, 'Veltech Dr. RR and Dr. SR University (VelTech, VTU), Avadi, Chennai\n', 'Chennai', 'mba', ' CAT,MAT,XAT,GMAT,TANCET MBA ', '2 years', 'UGC Approved', '1.8 lakhs', 'Integrated MBA in Logistics Management, 2 Years\r\nMaster of Business Administration, 2 Years\r\nM.Phil., 2 Years\r\nPh.D, 5 Years\r\nMBA in Automobile Dealerships Management in Collaboration with Kuttukaran Institute of HRD, 2 Years\r\nMBA in Digital Marketing in collaboration with Sprottshaw College, British Columbia, 2 Years\r\nMBA in Global Relations in collaboration with Sprottshaw College, British \r\n', 'veltech dr. rr and dr. sr university (veltech, vtu), avadi, chennai , mba , cat , mat , xat , gmat , tancet mba'),
(162, 'Bharath University (BU, Chennai), Selaiyur, Chennai\r\n', 'Chennai', 'mba', 'No Exam Required', '2 years', 'UGC Approved', '80,000', 'Master of Business Administration, 2 Years\r\nMBA in Hospital and Health System Management, 2 Years\r\nMBA in Marketing, 2 Years\r\nMBA in Banking and Finance, 2 Years\r\nMBA in International Business, 2 Years\r\nPhD in Management, 3 Years\r\nPhD in Management, 3 Years\r\nMBA in Tourism and Hospitality Management, 2 Years\r\n', 'Bharath University (BU, Chennai), Selaiyur , Chennai ,mba'),
(163, 'Chennai Business School (CBS, Chennai), Mylapore, Chennai\r\n', 'Chennai', 'mba', 'CAT,MAT,XAT,ATMA,GMAT', '1 years', '', '6,00,000 ', 'Post Graduate Program in Human Resource Management, 1 Year\r\nPost Graduate Program in Information Technology, 1 Year\r\nPost Graduate Program in Marketing and Communications, 1 Year\r\nPost Graduate Program in Finance, 1 Year\r\nPost Graduate Program in International Business, 1 Year\r\nPost Graduate Program in Entrepreneurship, 1 Year\r\n\r\n', 'chennai business school (cbs, chennai), mylapore, chennai , mba , cat ,mat,xat ,atma ,gmat'),
(164, 'Meenakshi Sundararajan School of Management, Kodambakkam, Chennai\n', 'Chennai', 'mba', 'CAT,MAT,XAT', '2 years', 'AICTE Approved', '3,50,000 ', 'Master of Business Administration, 2 Years\r\nPost Graduate Diploma in Management, 2 Years\r\n', 'meenakshi sundararajan school of management, kodambakkam, chennai , mba , cat,mat,xat'),
(165, 'Great Lakes Institute of Management (GLIM, Chennai), Kanchipuram, Chennai\n', 'Chennai', 'mba', 'CAT,CMAT,XAT,GMAT', '1 years', 'AICTE Approved', '15,30,000 ', 'Post Graduate Programme in Management, 1 Year\r\nPost Graduate Diploma in Management, 2 Years\r\n', 'great lakes institute of management (glim, chennai), kanchipuram, chennai , mba , cat,cmat,xat,gmat'),
(166, 'Institute of Public Enterprise (IPE, Hyderabad), Shamirpet, Hyderabad\r\n', 'Hyderabad', 'mba', 'CAT,MAT,CMAT,XAT,ATMA', '2 years', 'AICTE Approved', '8,10,000 ', 'Post Graduate Diploma in Management, 2 Years\r\nPost Graduate Diploma in Retail Marketing, 2 Years\r\nPost Graduate Diploma in Banking, Insurance and Financial Services, 2 Years\r\nPost Graduate Diploma in International Business, 2 Years\r\nPost Graduate Diploma in Human Resource Management, 2 Years\r\n', 'institute of public enterprise (ipe, hyderabad), shamirpet, hyderabad ,mba , cat,mat,cmat,xat,atma'),
(167, 'Hyderabad Business School, GITAM University (GHBS), Patancheru, Hyderabad\r\n', 'Hyderabad', 'mba', 'CAT,MAT,XAT,ATMA,GMAT', '2 years', 'UGC Approved', '6,60,780 ', 'Master of Business Administration, 2 Years\r\n', 'hyderabad business school, gitam university (ghbs), patancheru, hyderabad , mba , cat,mat,xat,atma,gmat'),
(168, 'Anglophile Business School, Madhapur, Hyderabad\n', 'Hyderabad', 'mba', 'CAT,MAT,CMAT,XAT,ATMA', '2 years', 'AICTE Approved, UGC Approved, DEC Approved', '3,60,000 ', 'Post Graduate Diploma in Management, 2 Years\r\nPGDM in Business Analytics, 2 Years\r\nPGDM in Pharma and Health Care Management, 2 Years\r\n', 'anglophile business school, madhapur, hyderabad ,mba ,cat,mat,cmat,xat,atma'),
(169, 'IIRM (Promoted by IRDAI), Gachibowli, Hyderabad\n', 'Hyderabad', 'mba', 'CAT,MAT,CMAT,XAT,ATMA', '2 years', 'AICTE Approved', '6,60,000', 'Post Graduate Diploma in Management, 2 Years\r\nPost Graduate Diploma in Business Analytics, 1 Year\r\n', 'iirm (promoted by irdai), gachibowli, hyderabad ,mba, cat,mat,cmat,xat,atma'),
(170, 'Administrative Staff College of India, Banjara Hills, Hyderabad\n', 'Hyderabad', 'mba', 'CAT,MAT,CMAT,XAT,GMAT', '2 years', 'AICTE Approved', '5,00,000 ', 'Postgraduate Program in Hospital Management, 2 Years\r\n', 'administrative staff college of india, banjara hills, hyderabad, mba, cat,mat,cmat,xat,gmat'),
(171, 'International Institute of Petroleum Pharma, Telecom & Management, Panjagutta, Hyderabad\r\n', 'Hyderabad', 'mba', 'CAT,MAT,XAT,ATMA', '2 years', 'AICTE Approved, UGC Approved, DEC Approved', '', 'M.B.A Petroleum & Energy Management, 2 Years\r\nM.B.A Telecom Management, 2 Years\r\nM.B.A Pharmaceutical Management, 2 Years\r\nM.B.A Hospital Management, 2 Years\r\nM.B.A Banking & Finance Management, 2 Years\r\n', 'international institute of petroleum pharma, telecom & management, panjagutta, hyderabad ,mba , cat,mat,xat,atma'),
(172, 'Aurora Group of Institutions (Aurora, Hyderabad), Chikkadpally, Hyderabad\n', 'Hyderabad', 'mba', 'CAT,MAT,CMAT,XAT,GMAT', '2 years', 'AICTE Approved', '6.0 lakhs', 'PGDM in Marketing, 2 Years\r\nPGDM in Hospital Management, 2 Years\r\nPGDM in Rural Management, 2 Years\r\n', 'aurora group of institutions (aurora, hyderabad), chikkadpally, hyderabad ,mba ,cat,mat,cmat,xat,gmat'),
(173, 'Siva Sivani Institute of Management (SSIM Hyderabad), Kompalli, Hyderabad\n', 'Hyderabad', 'mba', 'CAT,MAT,CMAT,XAT,GMAT ', '2 years', 'AICTE Approved', '7,25,000', 'PGDM (Triple Specialization), 2 Years\r\nPGDM in Human Resource Management, 2 Years\r\nPGDM in Marketing, 2 Years\r\nPGDM in Banking, Insurance, Finance and Allied Services, 2 Years\r\n', 'siva sivani institute of management (ssim hyderabad), kompalli, hyderabad ,mba, cat,mat,cmat,xat,gmat'),
(174, 'GBS School of Business Studies, Banjara Hills, Hyderabad\r\n', 'Hyderabad', 'mba', 'CAT,MAT,ATMA,ICET', '2 years', '', '4,50,000 ', 'Post Graduate Diploma in Management, 2 Years\r\nPGDM in Media, 2 Years\r\nPGDM in Healthcare, 2 Years\r\nPGDM in Retail Business, 2 Years\r\nPGDM in Business Analytics, 2 Years\r\n', 'gbs school of business studies, banjara hills, hyderabad ,mba, cat,mat,atma,icet'),
(175, 'Symbiosis National Aptitude Test (SNAP), Hyderabad, Mahboobnagar, Hyderabad\n', 'Hyderabad', 'mba', 'SNAP', '2 years', '', '9,75,000 ', 'MBA- SIBM (Hyderabad), 2 Years\r\nMBA- SIMC, 2 Years\r\nMBA-SICSR, 2 Years\r\nMBA-SIIB, 2 Years\r\nMBA-SIMS, 2 Years\r\nMBA- SITM, 2 Years\r\nMBA-SCIT, 2 Years\r\nMBA-SIOM, 2 Years\r\nMBA-SIHS, 2 Years\r\nMBA-SIBM (Bangalore), 2 Years\r\nMBA-SCMHRD, 2 Years\r\nMBA-SIBM (Pune), 2 Years\r\nMBA- SSBF, 2 Years\r\nMBA – SSMC (Bengaluru), 2 Years\r\n', 'symbiosis national aptitude test (snap), mahboobnagar, hyderabad , mba , snap'),
(176, 'ASM''s Institute of International Business and Research (IIBR), Pimpri, Pune\r\n', 'pune', 'mba', 'CAT,MAT,CMAT,XAT,GMAT', '2 years', 'AICTE Approval', '8,00,000', 'PGDM in Business Analytics and Big Data, 2 Years\r\nPGDM in Business Administration, 2 Years\r\nMBA-City U Seattle, USA, 2 Years\r\nMaster of Business Administration, 2 Years\r\n', 'asm''s institute of international business and research (iibr), pimpri, pune ,mba , cat,mat,cmat,xat,gmat'),
(177, 'International Institute of Management Studies, Pune (IIMS Pune), Hinjewadi, Pune\r\n', 'pune', 'mba', 'CAT,MAT,CMAT,XAT,ATMA', '2 years', 'AICTE Approved', '6,66,000 (E', 'Post Graduate Diploma in Management, 2 Years\r\nPost Graduate Diploma in Retail Management, 2 Years\r\n', 'international institute of management studies, pune (iims pune), hinjewadi, pune ,mba , cat,mat, cmat, xat, atma'),
(178, 'Sri Balaji Society''s- BIMM, BIIB, BITM and BIMHRD, Tathawade, Pune\r\n', 'pune', 'mba', 'CAT,MAT,CMAT,XAT,MAH-CET', '2 years', 'AICTE Approved', '6,60,000 ', 'BIMM - PGDM, 2 Years\r\nBIMM - PGDM in Information Technology and Marketing, 2 Years\r\nBIMM - PGDM in Personnel Management and Human Resource Management, 2 Years\r\nBIMHRD - PGDM, 2 Years\r\nBIMHRD - PGDM in Personnel Management and Human Resource Management, 2 Years\r\nBIMHRD - PGDM in Marketing and Finance, 2 Years\r\nBIIB - PGDM in Finance, 2 Years\r\nBIIB - PGDM in International Business, 2 Years\r\nBIIB - PGDM in Marketing, 2 Years\r\nBITM - PGDM in Marketing and Finance, 2 Years\r\nBITM - PGDM in Telecom, 2 Years\r\nBITM - PGDM in Telecom and Marketing, 2 Years\r\n', 'sri balaji society''s- bimm, biib, bitm and bimhrd, tathawade, pune, mba , cat,mat,cmat,xat,mah-cet'),
(179, 'Management Institute For Leadership and Excellence,(MILE Pune), Wagholi\n', 'pune', 'mba', 'CAT,MAT,CMAT,XAT,ATMA', '2 years', 'aICTE Approved', '5,93,000 ', 'Post Graduate Diploma in Management, 2 Years\r\n', 'management institute for leadership and excellence,(mile pune), wagholi , pune, mba , cat,mat,cmat,xat,atma'),
(180, 'Suryadatta Institute of Management and Mass Communication (SIMMC), Bavdhan, Pune\r\n', 'pune', 'mba', 'CAT,MAT,CMAT,ATMA,MAH-CET', '2 years', 'AICTE Approveda', '5,50,000 ', 'Post Graduate Diploma in Management, 2 Years\r\nMaster of Business Administration, 2 Years\r\n', 'suryadatta institute of management and mass communication (simmc), bavdhan , pune, mba , cat,mat,cmat,atma,mah-cet'),
(181, 'Padmashree Dr. D.Y.Patil Institute of Master of Business Administration (DYPIMBA), Akurdi, Pune\n', 'pune', 'mba', 'CAT,MAT,XAT,ATMA', '2 years', 'AICTE Approvedaa', '1,81,036', 'Master of Business Administration, 2 Years\r\n', 'padmashree dr. d.y.patil institute of master of business administration (dypimba), akurdi, pune , mba , cat,mat,xat,atma'),
(182, 'Deccan Education Society - Institute of Management Development and Research (IMDR), Deccan, Pune\n', 'pune', 'mba', 'CAT,MAT,CMAT,XAT,ATMA', '2 years', 'AICTE Approved', '3,50,000', 'Post Graduate Diploma in Management, 2 Years\r\n', 'deccan education society - institute of management development and research (imdr), deccan, pune , mba ,cat,mat, cmat,xat,atma'),
(183, 'Dnyansagar Institute of Management and Research (DIMR, Pune), Baner, Pune\n', 'pune', 'mba', 'CAT,MAT,CMAT,ATMA,GMAT', '2 years', 'AICTE Approved', '3,70,000 ', 'MBA + PGPM, 2 Years\r\n', 'dnyansagar institute of management and research (dimr, pune), baner, pune , mba , cat,mat,cmat,atma,gmat'),
(184, 'Indira College of Engineering and Management (ICEM), Parandwadi, Pune\n', 'pune', 'mba', 'CAT,MAT,XAT,ATMA,GMAT', '2 years', 'AICTE Approvedaa', '2,83,500', 'Master of Business Administration, 2 Years\r\n', 'indira college of engineering and management (icem), parandwadi, pune ,mba ,cat,mat, xat,atma,gmat'),
(185, 'Vishwakarma Global Business School (VGBS), Kondhwa Budruk, Pune\r\n', 'pune', 'mba', 'CAT,MAT,CMAT,XAT,ATMA', '2 years', 'AICTE Approved', '3,50,000 ', 'PGDM in Mass Communication, 2 Years\r\nPGDM in Finance, 2 Years\r\nPGDM in Event Management, 2 Years\r\nPGDM in Logistics and Supply Chain Management, 2 Years\r\nPGDM in Human Resource Management, 2 Years\r\nPGDM in Construction Management, 2 Years\r\nPGDM in Marketing Management, 2 Years\r\nPGDM in Agri Business Management, 2 Years\r\n', 'vishwakarma global business school (vgbs), kondhwa budruk, pune ,mba , cat,mat,cmat,xat,atma'),
(186, 'Calcutta Business School, Diamond Harbour Road, Kolkata\r\n', 'kolkata', 'mba', 'CAT,MAT,CMAT,GMAT', '2 years', 'AICTE Approved', '6,85,000 ', 'Post Graduate Diploma in Management, 2 Years\r\n', 'calcutta business school, diamond harbour road, kolkata ,mba , cat,mat,cmat,gmat'),
(187, 'Future Business School-FIEM, Sonarpur, Kolkata\r\n', 'kolkata', 'mba', 'MAT,CMAT,JEMAT', '2 years', 'AICTE Approved', '470000', 'Master of Business Administration, 2 Years\r\n', 'future business school-fiem, sonarpur, kolkata , mba , mat,cmat,jemat'),
(188, 'International Management Institute, Kolkata (IMI, Kolkata), Alipore, Kolkata\n', 'kolkata', 'mba', 'CAT,XAT,GMAT', '2 years', 'AICTE Approved', '10,95,350', 'Post Graduate Diploma in Management, 2 Years\r\n', 'international management institute, kolkata (imi, kolkata), alipore, kolkata ,mba , cat,xat,gmat'),
(189, 'International School of Business & Media, Kolkata, Rajarhat, Kolkata\r\n', 'kolkata', 'mba', 'CAT,MAT,CMAT,XAT,ATMA', '2 years', 'AICTE Approved', '6,40,000 ', 'PGPBM + PGDM, 2 Years\r\nPGPSCOM+PGDM, 2 Years\r\nPGPCM+PGDM, 2 Years\r\n', 'international school of business & media, kolkata, rajarhat, kolkata , mba , cat,mat,cmat,xat,atma'),
(190, 'Budge Budge Institute of Technology (BBIT), Budge Budge, Kolkata\n', 'kolkata', 'mba', 'MAT', '2 Years Full Time', 'AICTE Approved', '', 'Master of Business Administration, 2 Years\r\n', 'budge budge institute of technology (bbit), budge budge, kolkata ,mba ,mat'),
(191, 'Amity University, Kolkata, Kadampukur, Kolkata\n', 'kolkata', 'mba', ' MAT,CAT,XAT,NMAT,GMAT ', '2 Years Full Time', 'UGC Approved', '7,23,150 ', 'Master of Business Administration', 'amity university, kolkata, kadampukur, kolkata ,mba , mat,cat,xat,nmat,gmat'),
(192, 'Parjananananda Institute For Professional Studies, A.J.C. Bose Road, Kolkata\r\n', 'kolkata', 'mba', 'No Exam Required', '1 years', 'AICTE Approved, UGC Approved, DEC Approved', 'Rs. 2,50,000', '"Master of Business Administration, 2 Years\r\nMBA-Lateral entry, 1 Year\r\nPost Graduate Diploma in Business Management, 1 Year"\r\n', 'parjananananda institute for professional studies, a.j.c. bose road, kolkata , mba');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `college`
--
ALTER TABLE `college`
  ADD PRIMARY KEY (`cid`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
